apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: marouanedbibih/hyundai-sales-backend:latest
          ports:
            - containerPort: 8082
              name: spring
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mysql-host
            - name: SPRING_DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mysql-port
            - name: SPRING_DATASOURCE_DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mysql-db
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: cors-allowed-origins
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8082
          #   initialDelaySeconds: 90
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8082
          #   initialDelaySeconds: 90
          #   periodSeconds: 30