apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyundai-sales-backend
  labels:
    app: hyundai-sales
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hyundai-sales
      tier: backend
  template:
    metadata:
      labels:
        app: hyundai-sales
        tier: backend
    spec:
      containers:
        - name: hyundai-sales-backend
          image: marouanedbibih/hyundai-sales-backend:latest
          ports:
            - containerPort: 8082
              name: spring
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hyundai-sales-mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hyundai-sales-mysql-secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hyundai-sales-backend-config
                  key: host
            - name: SPRING_DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hyundai-sales-backend-config
                  key: port
            - name: SPRING_DATASOURCE_DB
              valueFrom:
                configMapKeyRef:
                  name: hyundai-sales-backend-config
                  key: db
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: hyundai-sales-backend-config
                  key: cors-allowed-origins
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10