apiVersion: v1
kind: Service
metadata:
  name: hyundai-sales-backend-service
  labels:
    app: hyundai-sales
    tier: backend
spec:
  selector:
    app: hyundai-sales
    tier: backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort