pipeline {
    agent any

    tools {
        maven 'maven-3.8.7'
        jdk 'jdk-21.0.7'
    }


    stages {

        stage("Code Checkout") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/marouanedbibih/hyundai-sales'
            }
        }

        stage("") {
            
        }
    }

}