apiVersion: v1
kind: Service
metadata:
  name: hyundai-sales-mysql
  labels:
    app: hyundai-sales-mysql
    tier: database
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: hyundai-sales-mysql
    tier: database