apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyundai-sales.fullname" . }}-backend-config
  labels:
    {{- include "hyundai-sales.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  SPRING_DATASOURCE_HOST: "{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local"
  SPRING_DATASOURCE_PORT: {{ .Values.mysql.port | quote }}
  SPRING_DATASOURCE_DB: {{ .Values.mysql.auth.database | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
  SPRING_PROFILES_ACTIVE: "docker"