apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyundai-sales.fullname" . }}-backend
  labels:
    {{- include "hyundai-sales.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "hyundai-sales.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "hyundai-sales.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "hyundai-sales.fullname" . }}-backend-config
            - secretRef:
                name: {{ include "hyundai-sales.fullname" . }}-backend-secret
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}