apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyundai-sales.fullname" . }}-backend-secret
  labels:
    {{- include "hyundai-sales.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.auth.username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}