services:
  # MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyundai_sales_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - hyundai-sales-net

# Volumes
volumes:
  mysql:

# Networks
networks:
  hyundai-sales-net:
    driver: bridge