
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: hyundai-sales-backend
    volumes:
      - backend-app:/app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hyundai_sales_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - hyundai-sales-net