services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: hyundai-sales-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyundai_sales_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hyundai-sales-net

# Volumes
volumes:
  mysql:
  backend-app:

# Networks
networks:
  hyundai-sales-net:
    driver: bridge