
services:
  backend:
    image: marouanedbibih/hyundai-sales-backend:latest
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hyundai-sales-mysql-db-container:3306/hyundai_sales_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: http://hyundai-sales.marouanedbibih.engineer
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - hyundai-sales-net
      - shared_network

  frontend:
    image: marouanedbibih/hyundai-sales-frontend:latest
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - backend
    networks:
      - hyundai-sales-net
      - shared_network


networks:
  shared_network:
    external: true
    name: shared_network