services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: hyundai-sales-backend
    restart: on-failure
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_HOST: hyundai-sales-mysql-db-container
      SPRING_DATASOURCE_PORT: 3306
      SPRING_DATASOURCE_DB: hyundai_sales_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - hyundai-sales-net

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8083
    container_name: hyundai-sales-frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - hyundai-sales-net
