apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyundai-sales.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "hyundai-sales.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hyundai-sales.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend