spring:
  profiles:
    active:
    - local
  application:
    name: hyundai-sales-backend

server:
  port: 8082
  
logging:
  level:
    org.springframework: DEBUG
    hibernate: DEBUG
    security: TRACE
    # Debug mysql
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

# public:
#   urls:
#     - "/swagger-ui/**"
#     - "/swagger-ui.html"
#     - "/v3/api-docs/**"
#     - "/api-docs/**"
#     - "/swagger-resources/**"
#     - "/webjars/**"
#     - "/actuator/**"
