spring:
  profiles:
    active:
    - local
  application:
    name: hyundai-sales-backend

server:
  port: 8082
  
logging:
  level:
    org.springframework: DEBUG
    hibernate: DEBUG
    security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/swagger-ui.html
