spring:
  profiles:
    active:
    - local
  application:
    name: hyundai-sales-backend

server:
  port: 8082
  
logging:
  level:
    org.springframework: DEBUG
    hibernate: DEBUG
    security: TRACE
    # Debug mysql
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: loan-service
  tracing:
    sampling:
      probability: 1.0
