# Global settings
global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""


# MySQL configuration using Bitnami chart
mysql:
  enabled: true
  auth:
    database: hyundai_sales
    username: hyundai_user
    password: "strongpassword!123"
    rootPassword: "strongrootpassword!123"
  primary:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi