# Global settings
global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: "hyundai-sales"

# MySQL configuration using Bitnami chart
mysql:
  port: 3306
  enabled: true
  auth:
    database: hyundai_sales
    username: hyundai_user
    password: "strongpassword!123"
    rootPassword: "strongrootpassword!123"
  primary:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

# Backend configurations
backend:
  enabled: true
  name: backend
  replicaCount: 1
  image:
    repository: marouanedbibih/hyundai-sales-backend
    tag: v2.0.1
    pullPolicy: IfNotPresent
  containerPort: 8082
  service:
    type: ClusterIP
    port: 8082
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 60
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 30
    periodSeconds: 10
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    hosts:
      - host: api.hyundai-sales.marouanedbibih.studio
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - api.hyundai-sales.marouanedbibih.studio
        secretName: hyundai-sales-api-tls

# CORS configuration
cors:
  allowedOrigins: "https://hyundai-sales.marouanedbibih.studio"



frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: marouanedbibih/hyundai-sales-frontend
    tag: prod-v2.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: hyundai-sales.marouanedbibih.studio
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - hyundai-sales.marouanedbibih.studio
        secretName: hyundai-sales-frontend-tls