name: Main Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yaml"
      - "frontend/**"
      - "backend/**"
      - "docker/**"
      - "k8s/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/main.yaml"
      - "frontend/**"
      - "backend/**"
      - "docker/**"
      - "k8s/**"
  release:
    types: [created]

env:
  # Backend
  BACKEND_WORKING_DIRECTORY: "backend"
  BACKEND_DOCKER_IMAGE_NAME: "hyundai-sales-backend"
  BACKEND_DOCKER_IMAGE_TAG: "latest"
  # Frontend
  FRONTEND_WORKING_DIRECTORY: "frontend"
  FRONTEND_DOCKER_IMAGE_NAME: "hyundai-sales-frontend"
  FRONTEND_DOCKER_IMAGE_TAG: "latest"

jobs:
  Backend-Continuous-Integration:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: "21"
          distribution: "temurin"
          java-package: "jdk"

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: ${{ env.BACKEND_WORKING_DIRECTORY }}
        run: mvn clean package

      - name: Run maven tests
        working-directory: ${{ env.BACKEND_WORKING_DIRECTORY }}
        run: mvn test jacoco:report

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ env.BACKEND_WORKING_DIRECTORY}}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: backend/.scannerwork/report-task.txt
          pollingTimeoutSec: 600
          working-directory: ${{ env.BACKEND_WORKING_DIRECTORY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_DOCKER_IMAGE_NAME }}:${{ env.BACKEND_DOCKER_IMAGE_TAG}} -f docker/Dockerfile.backend .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push docker image to repository
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_DOCKER_IMAGE_NAME }}:${{ env.BACKEND_DOCKER_IMAGE_TAG }}

  Frontend-Continuous-Integration:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    needs: Backend-Continuous-Integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}

      - name: Run tests
        run: npm run test --coverage
        working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ env.FRONTEND_WORKING_DIRECTORY}}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: ${{ env.FRONTEND_WORKING_DIRECTORY}}/.scannerwork/report-task.txt
          pollingTimeoutSec: 600
          working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.FRONTEND_WORKING_DIRECTORY }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_DOCKER_IMAGE_NAME }}:${{ env.FRONTEND_DOCKER_IMAGE_TAG}} -f docker/Dockerfile.frontend .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push docker image to repository
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_DOCKER_IMAGE_NAME}}:${{ env.FRONTEND_DOCKER_IMAGE_TAG }}
